#!/usr/bin/env python3
"""
Generate src/gui/embedded_assets.c from PNG/ICO files in resources/.

Scans resources/ for all image files, converts each to a C byte array,
and writes embedded_assets.c + embedded_assets.h.

Usage:
    python3 tools/generate_embedded_assets.py
    python3 tools/generate_embedded_assets.py --dry-run   # List files, don't write
"""

import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
RESOURCES = ROOT / "resources"
OUT_C = ROOT / "src" / "gui" / "embedded_assets.c"
OUT_H = ROOT / "src" / "gui" / "embedded_assets.h"

# Subdirectories to scan, in order
SCAN_DIRS = [
    "amps", "buttons", "cables", "cabs", "knobs", "leds",
    "mics", "pedals", "studio", "theme", "logo", "icon",
]

EXTENSIONS = {".png", ".ico"}


def collect_assets():
    """Collect all asset files, sorted by directory then name."""
    assets = []
    for subdir in SCAN_DIRS:
        d = RESOURCES / subdir
        if not d.is_dir():
            continue
        for f in sorted(d.iterdir()):
            if f.suffix.lower() in EXTENSIONS and f.is_file():
                rel = f.relative_to(ROOT)
                assets.append((str(rel), f))
    return assets


def format_bytes(data, indent="    "):
    """Format binary data as C hex array lines (16 bytes per line)."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ",".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"{indent}{hex_vals},")
    return "\n".join(lines)


def generate_c(assets):
    """Generate the full embedded_assets.c content."""
    parts = []
    parts.append("/* Auto-generated by tools/generate_embedded_assets.py — do not edit */")
    parts.append('#include "embedded_assets.h"')
    parts.append("#include <string.h>")
    parts.append("")

    # Emit each asset as a static byte array
    for i, (rel_path, full_path) in enumerate(assets):
        data = full_path.read_bytes()
        parts.append(f"/* {rel_path} ({len(data)} bytes) */")
        parts.append(f"static const unsigned char asset_{i}[] = {{")
        parts.append(format_bytes(data))
        parts.append("};")
        parts.append("")

    # Emit the asset table
    count = len(assets)
    parts.append(f"const fx_embedded_asset_t fx_embedded_assets[{count}] = {{")
    for i, (rel_path, full_path) in enumerate(assets):
        size = full_path.stat().st_size
        parts.append(f'    {{ "{rel_path}", asset_{i}, {size} }},')
    parts.append("};")
    parts.append("")

    parts.append(f"const int fx_embedded_asset_count = {count};")
    parts.append("")

    # Lookup function
    parts.append("const fx_embedded_asset_t *fx_embedded_find(const char *path) {")
    parts.append(f"    for (int i = 0; i < {count}; i++) {{")
    parts.append("        if (strcmp(fx_embedded_assets[i].path, path) == 0)")
    parts.append("            return &fx_embedded_assets[i];")
    parts.append("    }")
    parts.append("    return (void*)0;")
    parts.append("}")
    parts.append("")

    return "\n".join(parts)


def generate_h(count):
    """Generate embedded_assets.h."""
    return f"""/* Auto-generated by tools/generate_embedded_assets.py — do not edit */
#ifndef FX_EMBEDDED_ASSETS_H
#define FX_EMBEDDED_ASSETS_H

#include <stddef.h>

typedef struct {{ const char *path; const unsigned char *data; size_t size; }} fx_embedded_asset_t;

extern const fx_embedded_asset_t fx_embedded_assets[{count}];
extern const int fx_embedded_asset_count;

/* Look up an embedded asset by path. Returns NULL if not found. */
const fx_embedded_asset_t *fx_embedded_find(const char *path);

#endif
"""


def main():
    dry_run = "--dry-run" in sys.argv

    assets = collect_assets()
    if not assets:
        print("ERROR: No assets found in resources/", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(assets)} assets:")
    total_bytes = 0
    for rel_path, full_path in assets:
        size = full_path.stat().st_size
        total_bytes += size
        print(f"  {rel_path} ({size:,} bytes)")
    print(f"Total: {total_bytes:,} bytes ({total_bytes / 1024 / 1024:.1f} MB)")

    if dry_run:
        print("\n--dry-run: not writing files")
        return

    print(f"\nGenerating {OUT_H}...")
    OUT_H.write_text(generate_h(len(assets)))

    print(f"Generating {OUT_C}...")
    OUT_C.write_text(generate_c(assets))

    print(f"Done — {OUT_C.stat().st_size / 1024 / 1024:.1f} MB written")


if __name__ == "__main__":
    main()
